"""Regenerates the synthetic .3dm fixtures used by backend and viewer tests.

    pip install rhino3dm && python make_fixtures.py

meshes.3dm       52 objects: 48 mesh boxes on PARTS/FOAM, 1 colored sphere (object color),
                 1 box on a hidden layer, 1 closed polyline curve, 1 point. Units mm.
brep_nomesh.3dm  2 Breps WITHOUT cached render meshes (box + sphere) + 1 mesh.
                 Simulates a file saved with "Save small" / generated by script.
blocks.3dm       1 instance definition (mesh box) + 5 instance references.
"""
import rhino3dm as r, math


def add_layer(f, name, rgb):
    l = r.Layer(); l.Name = name; l.Color = (rgb[0], rgb[1], rgb[2], 255)
    return f.Layers.Add(l)


def box_mesh(cx, cy, cz, s):
    m = r.Mesh(); h = s / 2.0
    for p in [(-h,-h,-h),(h,-h,-h),(h,h,-h),(-h,h,-h),(-h,-h,h),(h,-h,h),(h,h,h),(-h,h,h)]:
        m.Vertices.Add(cx+p[0], cy+p[1], cz+p[2])
    for a,b,c,d in [(0,3,2,1),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)]:
        m.Faces.AddFace(a,b,c,d)
    m.Normals.ComputeNormals(); m.Compact(); return m


def sphere_mesh(cx, cy, cz, rad, nu=24, nv=12):
    m = r.Mesh()
    for i in range(nv+1):
        th = math.pi*i/nv
        for j in range(nu):
            ph = 2*math.pi*j/nu
            m.Vertices.Add(cx+rad*math.sin(th)*math.cos(ph), cy+rad*math.sin(th)*math.sin(ph), cz+rad*math.cos(th))
    for i in range(nv):
        for j in range(nu):
            a = i*nu+j; b = i*nu+(j+1)%nu; c = (i+1)*nu+(j+1)%nu; d = (i+1)*nu+j
            m.Faces.AddFace(a,b,c,d)
    m.Normals.ComputeNormals(); m.Compact(); return m


def meshes():
    f = r.File3dm(); f.Settings.ModelUnitSystem = r.UnitSystem.Millimeters
    lay_parts = add_layer(f, 'PARTS', (200,60,40))
    lay_foam = add_layer(f, 'FOAM', (240,240,240))
    lay_ref = add_layer(f, 'REFERENCE', (40,120,220))
    lay_hidden = add_layer(f, 'HIDDEN', (120,120,120)); f.Layers[lay_hidden].Visible = False
    for i in range(8):
        for j in range(6):
            a = r.ObjectAttributes(); a.LayerIndex = lay_parts if (i+j) % 2 == 0 else lay_foam
            a.Name = f'block_{i}_{j}'; a.SetUserString('PART_ID', f'P{i}{j}')
            f.Objects.AddMesh(box_mesh(i*120.0, j*120.0, 0.0, 100.0), a)
    a = r.ObjectAttributes(); a.LayerIndex = lay_ref; a.Name = 'sphere_ref'
    a.ColorSource = r.ObjectColorSource.ColorFromObject; a.ObjectColor = (255,200,0,255)
    f.Objects.AddMesh(sphere_mesh(400,300,300,150), a)
    a = r.ObjectAttributes(); a.LayerIndex = lay_hidden; a.Name = 'hidden_box'
    f.Objects.AddMesh(box_mesh(-300,-300,0,80), a)
    a = r.ObjectAttributes(); a.LayerIndex = lay_ref
    pl = r.Polyline([r.Point3d(0,0,0), r.Point3d(1000,0,0), r.Point3d(1000,700,0), r.Point3d(0,700,0), r.Point3d(0,0,0)])
    f.Objects.AddCurve(pl.ToNurbsCurve(), a)
    f.Objects.AddPoint(r.Point3d(500,350,600), a)
    f.Write('meshes.3dm', 7)


def brep_nomesh():
    f = r.File3dm(); f.Settings.ModelUnitSystem = r.UnitSystem.Millimeters
    lay = add_layer(f, 'BREPS', (0,160,90))
    a = r.ObjectAttributes(); a.LayerIndex = lay; a.Name = 'box_brep'
    f.Objects.AddBrep(r.Brep.CreateFromBox(r.Box(r.BoundingBox(r.Point3d(0,0,0), r.Point3d(200,100,50)))), a)
    a = r.ObjectAttributes(); a.LayerIndex = lay; a.Name = 'sphere_brep'
    f.Objects.AddBrep(r.Brep.CreateFromSphere(r.Sphere(r.Point3d(400,50,25), 60)), a)
    a = r.ObjectAttributes(); a.LayerIndex = lay; a.Name = 'mesh_ok'
    f.Objects.AddMesh(box_mesh(-200,0,0,80), a)
    f.Write('brep_nomesh.3dm', 7)


def blocks():
    f = r.File3dm(); f.Settings.ModelUnitSystem = r.UnitSystem.Millimeters
    lay = add_layer(f, 'BLOCKS', (180,60,200))
    idx = f.InstanceDefinitions.Add('unit_box', 'test block', '', '', r.Point3d(0,0,0), (box_mesh(0,0,0,50),), (r.ObjectAttributes(),))
    idef = f.InstanceDefinitions[idx]
    for k in range(5):
        a = r.ObjectAttributes(); a.LayerIndex = lay; a.Name = f'ref_{k}'
        f.Objects.AddInstanceObject(r.InstanceReference(idef.Id, r.Transform.Translation(k*80.0, k*20.0, k*10.0)), a)
    f.Write('blocks.3dm', 7)


if __name__ == '__main__':
    meshes(); brep_nomesh(); blocks()
    for name in ['meshes.3dm', 'brep_nomesh.3dm', 'blocks.3dm']:
        g = r.File3dm.Read(name)
        print(name, 'objects', len(g.Objects), 'layers', len(g.Layers), 'idefs', len(g.InstanceDefinitions))
